name: 构建镜像并推送到Docker Hub
on: push

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 登录DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 构建并推送到Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ZhangWenZhi/docsify-ag-ds:latest