name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - gh-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@gh-pages

    - name: Build and Deploy
      uses: Zhang-WenZhi/docsify-ag-ds@gh-pages
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm i docsify-cli -g && docsify serve docs